'use client';

import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SidebarLayout } from "@/components/layouts/sidebar-layout";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function generateBreadcrumbs(pathname: string) {
  // Remove trailing slash and split path into segments
  const segments = pathname.replace(/\/$/, "").split("/").filter(Boolean);
  
  // Filter out the 'pages' segment for display but keep track of filtered segments
  const displaySegments = segments.filter(segment => segment !== 'pages');
  
  return displaySegments.map((segment, index) => {
    // Build the URL for this breadcrumb, including 'pages' in the path
    const href = "/pages/" + displaySegments.slice(0, index + 1).join("/");
    // Capitalize first letter and replace hyphens with spaces
    const label = segment.charAt(0).toUpperCase() + segment.slice(1).replace(/-/g, " ");
    
    return { href, label };
  });
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const breadcrumbItems = generateBreadcrumbs(pathname);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarLayout breadcrumbItems={breadcrumbItems}>
          {children}
        </SidebarLayout>
      </body>
    </html>
  );
}
